# Generated by Django 3.1.7 on 2021-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210325_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
