# Generated by Django 3.1.7 on 2021-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_trailfam'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
