# Generated by Django 3.1.7 on 2021-04-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20210428_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', upload_to='images/'),
        ),
    ]
